server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      #   - id: user-logout
      #     uri: http://localhost:8080
      #     predicates:
      #       - Path=/api/v1/user/logout
      #     filters:
      #       - RewritePath=/api/v1/user/(?<remaining>.*), /user/$\{remaining}

      #   - id: user-reissue-token
      #     uri: http://localhost:8080
      #     predicates:
      #       - Path=/api/v1/user/reissue-token
      #     filters:
      #       - RewritePath=/api/v1/user/(?<remaining>.*), /user/$\{remaining}

      #   - id: user-kakao-login
      #     uri: http://localhost:8080
      #     predicates:
      #       - Path=/api/v1/user/kakao-login
      #     filters:
      #       - RewritePath=/api/v1/user/(?<remaining>.*), /user/$\{remaining}

        - id: user-service
          uri: http://user-service-spring.user-service.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/user/**
            - Method=GET,POST,PUT,DELETE
          filters:
            # - AuthorizationHeaderFilter
            - RewritePath=/api/v1/user/(?<remaining>.*), /user/$\{remaining}

        - id: location-service
          uri: http://location-service-spring.location-service.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/location/**
          filters:
            # - AuthorizationHeaderFilter
            - RewritePath=/api/v1/location/(?<remaining>.*), /location/$\{remaining}
        - id: review-service
          uri: http://review-service-spring.review-service.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/review/**
          filters:
            # - AuthorizationHeaderFilter
            - RewritePath=/api/v1/review/(?<remaining>.*), /review/$\{remaining}
        - id: like-service
          uri: http://like-service-spring.like-service.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/like/**
          filters:
            # - AuthorizationHeaderFilter
            - RewritePath=/api/v1/like/(?<remaining>.*), /like/$\{remaining}
        # - id: category-service
        #   uri: http://category-service-spring.category-service.svc.cluster.local:8080
        #   predicates:
        #     - Path=/api/v1/category/**
        #   filters:
        #     - AuthorizationHeaderFilter
        #     - RewritePath=/api/v1/category/(?<remaining>.*), /category/$\{remaining}

jwt:
  secret: 3H4e3DlTawx8T0Ti79PKCeDhHngmQbuiUeSy80qAGn8=
